language: python
python: 3.5

matrix:
    include:
    #- dist: trusty
    #  env:
    #    - JOB="ASV"
    - dist: trusty
      env:
        - JOB="PIP"
    - dist: trusty
      env:
        - JOB="CONDA"

sudo: required

addons:
  apt:
    packages:
      - build-essential

before_install:
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - git clone https://github.com/pandas-dev/pandas
  - ci/install_miniconda.sh
  - ci/before_install.sh

install:
  - conda list
  - conda list -n pandas
  - ci/install.sh

script:
  - ci/script.sh
