name: pandas
dependencies:
  - Cython
  - matplotlib
  - nomkl
  - numexpr
  - numpy
  - openpyxl
  - pytables
  - pytest
  - python-dateutil
  - python=3
  - pytz
  - scipy
  - sqlalchemy
  - xlrd
  - xlsxwriter
  - xlwt
  - pip:
    - git+https://github.com/spacetelescope/asv
